---
title       : Is Your Weight Average for Your Height?
subtitle    : Developing Data Products - November 2015
author      : 
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Introduction to the Application

Most women don't know how their weight compares to that of the average person. This application tells female users between the ages of 30-39 whether they are below, equal to or above the average weight of women the same height.  The application takes the user's height and weight as input before running the comparison.  The application displays a plot of the data set. If their weight is in the range of weights on the plot, then a point is displayed showing where the user's weight compares.

--- 

## The Data Set

This application uses the Women Data Set that comes with R.  This data set gives the average heights and weights of women in America between the ages of 30-39.

```{r, echo=FALSE}

dataSet <- women
dataSet


```

--- 

## Easy to Use

This application is very easy to use.

Step 1: Enter your height in inches.
Note: The range of acceptable heights is from 58 to 72 inches.

Step 2: Enter your current weight.
Note: Your weight must be entered in lbs.

Step 3: Click the Submit button.
The application does the comparison.

Step 4: View the results.

--- 

## Getting Started

You can get started by visting the application here:

https://jsneaker.shinyapps.io/Shiny_App2


